imports and downloads

In [29]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

uploading the data

In [30]:
file = "C:/Users/pragy/Applied-Machine-Learning/Assignment2/smsspamcollection/SMSSpamCollection"

In [31]:
data=pd.read_csv(file, sep='\t', header=None, names=['Label', 'Mssg'])

In [32]:
data.head()

  Label                                               Mssg
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [33]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Label   5572 non-null   object
 1   Mssg    5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB
None

In [34]:
data.loc[data.Label == 'spam', 'Label'] = 1
data.loc[data.Label == 'ham', 'Label'] = 0

In [35]:
data.head()

  Label                                               Mssg
0     0  Go until jurong point, crazy.. Available only ...
1     0                      Ok lar... Joking wif u oni...
2     1  Free entry in 2 a wkly comp to win FA Cup fina...
3     0  U dun say so early hor... U c already then say...
4     0  Nah I don't think he goes to usf, he lives aro...

Train test split

In [36]:
train_X, test_X, train_Y, test_Y = train_test_split(data.Mssg, data.Label, test_size = 0.1, random_state = 42)

Train val split

In [37]:
train_X, val_X, train_Y, val_Y = train_test_split(train_X, train_Y, test_size = 0.1, random_state = 42)

In [38]:
## check seed 42 for data profile
print("Number of 0s and 1s in Train set are:")
print(train_Y.value_counts())

print("Number of 0s and 1s in Validation set are:")
print(val_Y.value_counts())

print("Number of 0s and 1s in Test set are:")
test_Y.value_counts()

Number of 0s and 1s in Train set are:
0    3899
1     613
Name: Label, dtype: int64
Number of 0s and 1s in Validation set are:
0    441
1     61
Name: Label, dtype: int64
Number of 0s and 1s in Test set are:

0    485
1     73
Name: Label, dtype: int64

In [39]:
df_train = pd.DataFrame(list(zip(train_X,train_Y)),columns=["Text",'Label'])
df_test = pd.DataFrame(list(zip(test_X,test_Y)),columns=["Text",'Label'])
df_val = pd.DataFrame(list(zip(val_X,val_Y)),columns=["Text",'Label'])
df_val.to_csv('Data/Validation Data.csv',index=False) 
df_test.to_csv('Data/Test Data.csv',index=False) 
df_train.to_csv('Data/Training Data.csv',index=False)

Repeating same for a different seed

In [40]:
train_X, test_X, train_Y, test_Y = train_test_split(data.Mssg, data.Label, test_size = 0.1, random_state = 95)
train_X, val_X, train_Y, val_Y = train_test_split(train_X, train_Y, test_size = 0.1, random_state = 95)

In [41]:
## check seed 95 for data profile
print("Number of 0s and 1s in Train set are:")
print(train_Y.value_counts())

print("Number of 0s and 1s in Validation set are:")
print(val_Y.value_counts())

print("Number of 0s and 1s in Test set are:")
test_Y.value_counts()

Number of 0s and 1s in Train set are:
0    3906
1     606
Name: Label, dtype: int64
Number of 0s and 1s in Validation set are:
0    432
1     70
Name: Label, dtype: int64
Number of 0s and 1s in Test set are:

0    487
1     71
Name: Label, dtype: int64

In [42]:
df_train = pd.DataFrame(list(zip(train_X,train_Y)),columns=["Text",'Label'])
df_test = pd.DataFrame(list(zip(test_X,test_Y)),columns=["Text",'Label'])
df_val = pd.DataFrame(list(zip(val_X,val_Y)),columns=["Text",'Label'])
df_val.to_csv('Data/Validation Data.csv',index=False) 
df_test.to_csv('Data/Test Data.csv',index=False) 
df_train.to_csv('Data/Training Data.csv',index=False)

Version for seed 42

In [43]:
train = pd.read_csv('Data/Training Data.csv')
val = pd.read_csv('Data/Validation Data.csv')
test = pd.read_csv('Data/Test Data.csv')

In [45]:
print("Number of 0s and 1s in Train set are:")
print(train["Label"].value_counts())

print("Number of 0s and 1s in Validation set are:")
print(val["Label"].value_counts())

print("Number of 0s and 1s in Test set are:")
print(test["Label"].value_counts())

Number of 0s and 1s in Train set are:
0    3899
1     613
Name: Label, dtype: int64
Number of 0s and 1s in Validation set are:
0    441
1     61
Name: Label, dtype: int64
Number of 0s and 1s in Test set are:
0    485
1     73
Name: Label, dtype: int64

Version for seed 95

In [46]:
train = pd.read_csv('Data/Training Data.csv')
val = pd.read_csv('Data/Validation Data.csv')
test = pd.read_csv('Data/Test Data.csv')

In [47]:
print("Number of 0s and 1s in Train set are:")
print(train["Label"].value_counts())

print("Number of 0s and 1s in Validation set are:")
print(val["Label"].value_counts())

print("Number of 0s and 1s in Test set are:")
print(test["Label"].value_counts())

Number of 0s and 1s in Train set are:
0    3906
1     606
Name: Label, dtype: int64
Number of 0s and 1s in Validation set are:
0    432
1     70
Name: Label, dtype: int64
Number of 0s and 1s in Test set are:
0    487
1     71
Name: Label, dtype: int64